mkdir -p .github/workflows
cat > .github/workflows/ci.yml << 'EOF'
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: ${{ matrix.python }}
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: pip install -e .
      - run: pytest --maxfail=1 --disable-warnings -q
      - run: black --check src tests
      - run: isort --check-only src tests
      - run: flake8 src tests
EOF
git add .github/workflows/ci.yml
git commit -m "ci: add GitHub Actions CI workflow"

